//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.LoadCartService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoadCartService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loadCart", ReplyAction="http://tempuri.org/IService1/loadCartResponse")]
        string[] loadCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/loadCart", ReplyAction="http://tempuri.org/IService1/loadCartResponse")]
        System.Threading.Tasks.Task<string[]> loadCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItems", ReplyAction="http://tempuri.org/IService1/organizedItemsResponse")]
        string[] organizedItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItems", ReplyAction="http://tempuri.org/IService1/organizedItemsResponse")]
        System.Threading.Tasks.Task<string[]> organizedItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItemsBySize", ReplyAction="http://tempuri.org/IService1/organizedItemsBySizeResponse")]
        string[] organizedItemsBySize();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItemsBySize", ReplyAction="http://tempuri.org/IService1/organizedItemsBySizeResponse")]
        System.Threading.Tasks.Task<string[]> organizedItemsBySizeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItemsByColor", ReplyAction="http://tempuri.org/IService1/organizedItemsByColorResponse")]
        string[] organizedItemsByColor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/organizedItemsByColor", ReplyAction="http://tempuri.org/IService1/organizedItemsByColorResponse")]
        System.Threading.Tasks.Task<string[]> organizedItemsByColorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OnlineShopping.LoadCartService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OnlineShopping.LoadCartService.IService1>, OnlineShopping.LoadCartService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] loadCart() {
            return base.Channel.loadCart();
        }
        
        public System.Threading.Tasks.Task<string[]> loadCartAsync() {
            return base.Channel.loadCartAsync();
        }
        
        public string[] organizedItems() {
            return base.Channel.organizedItems();
        }
        
        public System.Threading.Tasks.Task<string[]> organizedItemsAsync() {
            return base.Channel.organizedItemsAsync();
        }
        
        public string[] organizedItemsBySize() {
            return base.Channel.organizedItemsBySize();
        }
        
        public System.Threading.Tasks.Task<string[]> organizedItemsBySizeAsync() {
            return base.Channel.organizedItemsBySizeAsync();
        }
        
        public string[] organizedItemsByColor() {
            return base.Channel.organizedItemsByColor();
        }
        
        public System.Threading.Tasks.Task<string[]> organizedItemsByColorAsync() {
            return base.Channel.organizedItemsByColorAsync();
        }
    }
}
